services:
  - type: web
    name: sokko
    env: ruby
    plan: free
    numInstances: 1
    buildCommand: ./bin/render-build.sh
    startCommand: bundle exec puma -C config/deploy/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sokko-db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
databases:
  - name: sokko-db
    plan: free
    postgresMajorVersion: 16
